### ISSUE TITLE
File selector in Vue 3

### ISSUE THREAD

**Issue by makerovski** [d2phap/vue-file-selector#37]
Hello,

Is there a way I can use this component with my Vue 3 application ?

I used it many times in Vue 2 projects, but unfortunately I don't get it to work in Vue 3.

Thank you!

**Comment by d2phap** [comment]
Hi @makerovski 

I will update it with typescript support over the weekend.

**Comment by makerovski** [comment]
Hi @d2phap ,

Thank you very much, I use this many times and help me a lot. Apreciated!

**Comment by d2phap** [comment]
@makerovski updated Vuejs 3 + TypeScript!

**Comment by makerovski** [comment]
> @makerovski updated Vuejs 3 + TypeScript!

Thank you very much!!!
